python3 subset_sum.py -a b -i < data/input/input_10_of_100 | grep SOLUTION > data/output/$1
python3 subset_sum.py -a b -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_10_of_100 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_11_of_110 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_12_of_120 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_13_of_130 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_14_of_140 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_15_of_150 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a b -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a c -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a t -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
python3 subset_sum.py -a s -i < data/input/input_20_of_200 | grep SOLUTION >> data/output/$1
